name: After Deployment V4
on:
  deployment_status:
jobs:
  student:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    # if: github.event.deployment_status.state == 'success'
    if: github.event.deployment_status.environment == 'Preview â€“ nx-vercel-test-gh-action-after-deploy-app-one'

    steps:
    - uses: actions/checkout@v2
    - name: Check project namessssss
      run: echo "${{ toJSON(github.event.depolyment_status.target_url) }}"
    - name: Print all eventssssss
      run: echo "${{ toJSON(github.event) }}"
